// GENERATED by calculations/generate_hardware_dummies.py
// MP-04 ENVELOPE/BALLAST DUMMIES — NOT AIRWORTHY; NOT FLIGHT HARDWARE
// Dimensions are external catalog/bounded envelopes in millimetres.
// Connector sweeps, cooling volumes, tolerances and mounts are separate measurements.

PART = "pack_6s1p_p42a_flat_narrow";
$fn = 72;

module open_ballast_box(size) {
    wall = min([1.2, size[0]/4, size[1]/4, size[2]/2]);
    difference() {
        cube(size, center=false);
        translate([wall, wall, wall])
            cube([size[0]-2*wall, size[1]-2*wall, size[2]-wall+0.02], center=false);
    }
}

module open_motor_shell(length, diameter) {
    wall = min([1.2, length/3, diameter/5]);
    rotate([0, 90, 0]) difference() {
        cylinder(h=length, d=diameter);
        translate([0, 0, wall]) cylinder(h=length, d=diameter-2*wall);
    }
}

// pack_6s1p_p42a / flat-narrow; [D]: 3x2x1-A; maximum cells plus wrap, nickel and folded-lead allowance
module dummy_pack_6s1p_p42a_flat_narrow() {
    open_ballast_box([223.2, 44, 22.6]);
}

// pack_6s1p_p42a / flat-moderate; [D]: 6x1x1-B; maximum cells plus wrap, nickel and folded-lead allowance
module dummy_pack_6s1p_p42a_flat_moderate() {
    open_ballast_box([142.8, 70.8, 22.6]);
}

// pack_8s1p_p42a / flat-narrow; [D]: 4x2x1-A; maximum cells plus wrap, nickel and folded-lead allowance
module dummy_pack_8s1p_p42a_flat_narrow() {
    open_ballast_box([293.4, 44, 22.6]);
}

// pack_8s1p_p42a / flat-moderate; [D]: 8x1x1-B; maximum cells plus wrap, nickel and folded-lead allowance
module dummy_pack_8s1p_p42a_flat_moderate() {
    open_ballast_box([186.2, 70.8, 22.6]);
}

// fc_6s / body; [M]: manufacturer LxWxH
module dummy_fc_6s_body() {
    open_ballast_box([36.5, 36.5, 7]);
}

// pdb_6s / body-bound; [M]/[E]: planform and mass manufacturer data; thickness is an installation estimate
module dummy_pdb_6s_body_bound() {
    open_ballast_box([36.5, 36.5, 5]);
}

// fc_pdb_8s_class / station-bound; [D]/[E]: I-17 all-board service cavity; not a component body
module dummy_fc_pdb_8s_class_station_bound() {
    open_ballast_box([64, 45, 21]);
}

// elevon_servos / body; [M]: catalog LxWxH per servo
module dummy_elevon_servos_body() {
    open_ballast_box([22.5, 11.5, 24.6]);
}

// rudder_servo_reserve / reserved-pocket; [D]/[E]: I-18 catalog maximum plus clearance; deliberately larger than the reference part
module dummy_rudder_servo_reserve_reserved_pocket() {
    open_ballast_box([34, 16, 39]);
}

// o4_camera / body; [M]: DJI LxWxH
module dummy_o4_camera_body() {
    open_ballast_box([13.44, 12.36, 16.5]);
}

// o4_vtx_antenna / vtx-body; [M]: DJI transmission-module LxWxH; antenna route separate
module dummy_o4_vtx_antenna_vtx_body() {
    open_ballast_box([30, 30, 6]);
}

// gps_mag / body; [M]: manufacturer LxWxH
module dummy_gps_mag_body() {
    open_ballast_box([20, 20, 12.4]);
}

// pitot_sensor / board-bound; [E]: existing packaging bound; manufacturer mass but no released body dimensions in source
module dummy_pitot_sensor_board_bound() {
    open_ballast_box([30, 20, 10]);
}

// receiver / body; [M]: manufacturer LxWxH without antenna
module dummy_receiver_body() {
    open_ballast_box([10, 10, 3]);
}

// buzzer / class-bound; [E]: existing packaging allowance
module dummy_buzzer_class_bound() {
    open_ballast_box([15, 15, 10]);
}

// blackbox_card / card; [M]: MicroSD form factor
module dummy_blackbox_card_card() {
    open_ballast_box([15, 11, 1]);
}

// MN3110 KV470; https://store.tmotor.com/product/mn3110-motor-navigator-type.html
module dummy_tmotor_mn3110_kv470() {
    open_motor_shell(28.5, 37.7);
}

// MN4010 KV475; https://store.tmotor.com/product/mn4010-kv580-motor-navigator-type.html
module dummy_tmotor_mn4010_kv475() {
    open_motor_shell(30.5, 44.7);
}

// MN4010 KV370; https://store.tmotor.com/product/mn4010-kv580-motor-navigator-type.html
module dummy_tmotor_mn4010_kv370() {
    open_motor_shell(30.5, 44.7);
}

// MN4012 KV400; https://store.tmotor.com/product/mn4012-kv480-motor-navigator-type.html
module dummy_tmotor_mn4012_kv400() {
    open_motor_shell(32.5, 44.7);
}

// 80F3[X]v2; https://powerdrives.net/80f3
module dummy_apd_80f3x_v2_6s() {
    open_ballast_box([44, 22, 12]);
}

// FlyFun 60A V5; https://www.hobbywing.com/uploads/file/20220817/308d789701a8209b133476865a0ac754.pdf
module dummy_hobbywing_flyfun_60a_v5() {
    open_ballast_box([69, 35, 18]);
}

// 120F3[X]v2; https://powerdrives.net/120f3
module dummy_apd_120f3x_v2_8s() {
    open_ballast_box([70, 30, 20]);
}

// FlyFun 80A V5; https://www.hobbywing.com/uploads/file/20220817/308d789701a8209b133476865a0ac754.pdf
module dummy_hobbywing_flyfun_80a_v5() {
    open_ballast_box([70, 35, 19]);
}

if (PART == "pack_6s1p_p42a_flat_narrow") dummy_pack_6s1p_p42a_flat_narrow();
else if (PART == "pack_6s1p_p42a_flat_moderate") dummy_pack_6s1p_p42a_flat_moderate();
else if (PART == "pack_8s1p_p42a_flat_narrow") dummy_pack_8s1p_p42a_flat_narrow();
else if (PART == "pack_8s1p_p42a_flat_moderate") dummy_pack_8s1p_p42a_flat_moderate();
else if (PART == "fc_6s_body") dummy_fc_6s_body();
else if (PART == "pdb_6s_body_bound") dummy_pdb_6s_body_bound();
else if (PART == "fc_pdb_8s_class_station_bound") dummy_fc_pdb_8s_class_station_bound();
else if (PART == "elevon_servos_body") dummy_elevon_servos_body();
else if (PART == "rudder_servo_reserve_reserved_pocket") dummy_rudder_servo_reserve_reserved_pocket();
else if (PART == "o4_camera_body") dummy_o4_camera_body();
else if (PART == "o4_vtx_antenna_vtx_body") dummy_o4_vtx_antenna_vtx_body();
else if (PART == "gps_mag_body") dummy_gps_mag_body();
else if (PART == "pitot_sensor_board_bound") dummy_pitot_sensor_board_bound();
else if (PART == "receiver_body") dummy_receiver_body();
else if (PART == "buzzer_class_bound") dummy_buzzer_class_bound();
else if (PART == "blackbox_card_card") dummy_blackbox_card_card();
else if (PART == "tmotor_mn3110_kv470") dummy_tmotor_mn3110_kv470();
else if (PART == "tmotor_mn4010_kv475") dummy_tmotor_mn4010_kv475();
else if (PART == "tmotor_mn4010_kv370") dummy_tmotor_mn4010_kv370();
else if (PART == "tmotor_mn4012_kv400") dummy_tmotor_mn4012_kv400();
else if (PART == "apd_80f3x_v2_6s") dummy_apd_80f3x_v2_6s();
else if (PART == "hobbywing_flyfun_60a_v5") dummy_hobbywing_flyfun_60a_v5();
else if (PART == "apd_120f3x_v2_8s") dummy_apd_120f3x_v2_8s();
else if (PART == "hobbywing_flyfun_80a_v5") dummy_hobbywing_flyfun_80a_v5();
else echo(str("Unknown PART: ", PART));
