#!/usr/bin/env python3
"""Generate printable MP-04 envelope/ballast dummies as OpenSCAD source.

The output reproduces catalog or bounded external envelopes only.  It carries no
flight-strength, cooling, connector, tolerance or airworthiness authority.
"""
from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

import hardware_candidate_trade
import hardware_manifest


ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "geometry" / "equipment-dummies" / "mp04-envelope-dummies.scad"
SKIPPED_ENVELOPE_PREFIXES = ("route-bound", "distributed-allocation", "rotating-disk")
REPLACED_CLASS_IDS = {
    "motor_6s_class", "motor_8s_class", "esc_6s_class", "esc_8s_class"
}


@dataclass(frozen=True)
class Dummy:
    identifier: str
    label: str
    shape: str
    dimensions_mm: tuple[float, float, float]
    basis: str


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    if not slug:
        raise ValueError("dummy identifier cannot be empty")
    return slug


def dummies() -> tuple[Dummy, ...]:
    values: list[Dummy] = []
    for item in hardware_manifest.HARDWARE:
        if item.identifier in REPLACED_CLASS_IDS:
            continue
        for envelope in item.envelopes:
            if envelope.name.startswith(SKIPPED_ENVELOPE_PREFIXES):
                continue
            values.append(Dummy(
                _slug(f"{item.identifier}__{envelope.name}"),
                f"{item.identifier} / {envelope.name}", "box",
                envelope.dimensions_mm, f"{envelope.authority}: {envelope.basis}",
            ))
    for candidate in hardware_candidate_trade.MOTORS:
        values.append(Dummy(
            _slug(candidate.identifier), candidate.model, "motor",
            candidate.body_lwh_mm, candidate.source_url,
        ))
    for candidate in hardware_candidate_trade.ESCS:
        if "REJECT" in candidate.procurement_rank:
            continue
        values.append(Dummy(
            _slug(candidate.identifier), candidate.model, "box",
            candidate.body_lwh_mm, candidate.source_url,
        ))
    return tuple(values)


def _fmt(value: float) -> str:
    return f"{value:.3f}".rstrip("0").rstrip(".")


def _vector(values: tuple[float, float, float]) -> str:
    return "[" + ", ".join(_fmt(value) for value in values) + "]"


def generated_scad() -> str:
    values = dummies()
    lines = [
        "// GENERATED by calculations/generate_hardware_dummies.py",
        "// MP-04 ENVELOPE/BALLAST DUMMIES — NOT AIRWORTHY; NOT FLIGHT HARDWARE",
        "// Dimensions are external catalog/bounded envelopes in millimetres.",
        "// Connector sweeps, cooling volumes, tolerances and mounts are separate measurements.",
        "",
        f'PART = "{values[0].identifier}";',
        "$fn = 72;",
        "",
        "module open_ballast_box(size) {",
        "    wall = min([1.2, size[0]/4, size[1]/4, size[2]/2]);",
        "    difference() {",
        "        cube(size, center=false);",
        "        translate([wall, wall, wall])",
        "            cube([size[0]-2*wall, size[1]-2*wall, size[2]-wall+0.02], center=false);",
        "    }",
        "}",
        "",
        "module open_motor_shell(length, diameter) {",
        "    wall = min([1.2, length/3, diameter/5]);",
        "    rotate([0, 90, 0]) difference() {",
        "        cylinder(h=length, d=diameter);",
        "        translate([0, 0, wall]) cylinder(h=length, d=diameter-2*wall);",
        "    }",
        "}",
        "",
    ]
    for dummy in values:
        lines.extend([
            f"// {dummy.label}; {dummy.basis}",
            f"module dummy_{dummy.identifier}() {{",
        ])
        if dummy.shape == "motor":
            length, diameter, _diameter_2 = dummy.dimensions_mm
            lines.append(f"    open_motor_shell({_fmt(length)}, {_fmt(diameter)});")
        else:
            lines.append(f"    open_ballast_box({_vector(dummy.dimensions_mm)});")
        lines.extend(["}", ""])
    for index, dummy in enumerate(values):
        keyword = "if" if index == 0 else "else if"
        lines.append(f'{keyword} (PART == "{dummy.identifier}") dummy_{dummy.identifier}();')
    lines.extend([
        "else echo(str(\"Unknown PART: \", PART));",
        "",
    ])
    return "\n".join(lines)


def validation_checks() -> dict[str, bool]:
    values = dummies()
    identifiers = [dummy.identifier for dummy in values]
    return {
        "dummy identifiers are unique": len(identifiers) == len(set(identifiers)),
        "every dummy has positive external dimensions": all(
            all(value > 0.0 for value in dummy.dimensions_mm) for dummy in values
        ),
        "all non-rejected propulsion candidates have a dummy": all(
            _slug(candidate.identifier) in identifiers
            for candidate in (*hardware_candidate_trade.MOTORS, *hardware_candidate_trade.ESCS)
            if "REJECT" not in candidate.procurement_rank
        ),
        "generated OpenSCAD file is current": (
            OUTPUT_PATH.is_file()
            and OUTPUT_PATH.read_text(encoding="utf-8") == generated_scad()
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--render", action="store_true", help="print generated OpenSCAD")
    parser.add_argument("--write", action="store_true", help="write the canonical OpenSCAD file")
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()
    if args.render:
        print(generated_scad(), end="")
        return 0
    if args.write:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(generated_scad(), encoding="utf-8")
        print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
        return 0
    if args.check:
        checks = validation_checks()
        for name, passed in checks.items():
            print(f"[{'PASS' if passed else 'FAIL'}] {name}")
        return 0 if all(checks.values()) else 1
    checks = validation_checks()
    print(f"MP-04 envelope dummies: {len(dummies())}")
    for name, passed in checks.items():
        print(f"[{'PASS' if passed else 'FAIL'}] {name}")
    return 0 if all(checks.values()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
